[build-system]
requires = ["setuptools>=59.4"]
build-backend = "setuptools.build_meta"

[project]
name = "openroad-app-run_console"
version = "0.1.0"
description = "Run Console"
requires-python = ">=3.9"
dependencies = [
  "openroad-platform-client",
]

[project.scripts]
openroad-app-run_console = "openroad_app_run_console.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["openroad_app_run_console*"]
