[build-system]
requires = ["setuptools>=59.4"]
build-backend = "setuptools.build_meta"

[project]
name = "openroad-app-plan_executor"
version = "0.1.0"
description = "Execution Plan Service"
requires-python = ">=3.9"
dependencies = [
  "openroad-platform-client",
]

[project.scripts]
openroad-app-plan_executor = "openroad_app_plan_executor.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["openroad_app_plan_executor*"]
